### ISSUE TITLE
Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by Raphides** [fga-eps-mds/2022-2-Squad06#17]
## Descrição
Apresentar o design front-end das principais páginas através do protótipo de alta-fidelidade

## Tarefas
Prototipar páginas:
- [x] Home
- [x] About
- [x] Dashboard
- [x] Contact

## Critérios de Aprovação
- Ilustrar o design finalizado

**Comment by Raphides** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Esquadro-6-636ecc9a72dcd5dca72fdcb2/issues/fga-eps-mds/2022-2-Squad06/17?planning-poker) with Zenhub @JoaoBarreto03

**Comment by Raphides** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Esquadro-6-636ecc9a72dcd5dca72fdcb2/issues/fga-eps-mds/2022-2-Squad06/17?planning-poker) with Zenhub @guilhermekishimoto @YuriBre

**Comment by frmiza** [comment]
Prototipo de alta fidelidade terminado
