### ISSUE TITLE
Organização inicial do grupo

### ISSUE THREAD

**Issue by Raphides** [fga-eps-mds/2022-2-Squad06#2]
## Descrição
_Issue_ destinada à organização básica para a eficiência do grupo. Apresentações dos integrantes, configurações iniciais do ambiente do GitHub e divisão de papéis (do método Scrum) estão incluídos no processo.

## Tarefas
- [x] Entrada de todos no repositório
- [x] Apressentação do @Raphides
- [x] Apresentação do @guilhermekishimoto
- [x] Apresentação do @JoaoBarreto03 
- [x] Apresentação do @YuriBre 
- [x] Apresentação do @Danilo-Carvalho-Antunes
- [x] Apresentação do Mizael
- [x] Quem será o Scrum Master
- [x] Quem será o Product Owner

## Critérios de Aprovação
- Todos entraram no GitHub com sucesso.
- A apresentação de todos permitiu-nos entender quais os pontos fortes e interesses de cada integrante.
- Foram definidos todos os papéis do Método Scrum

**Comment by Raphides** [comment]
Foi feita a criação do site de documentação através do GitHub Pages.

**Comment by Raphides** [comment]
O _Scrum Master_ será @Raphides (sim, eu mesmo).

**Comment by Raphides** [comment]
A decisão do Product Owner será postergada para a próxima semana

**Comment by JoaoBarreto03** [comment]
Eu, @JoaoBarreto03, serei o Product Owner do nosso projeto.
