### ISSUE TITLE
À procura de Dashboards Creators

### ISSUE THREAD

**Issue by Raphides** [fga-eps-mds/2022-2-Squad06#43]
## Descrição
A atividade visa a busca por criadores de Dashboards que sejam compatíveis com o SQLite3 e todo o nosso ambiente virtual.
## Tarefas
- [x] Buscar criadores de Dashboards
- [x] Checar sugestões

## Sugestões:
- [x] Microsoft Power Bi
- [ ] Grafana
- [x] Gráficos em Matplot e outras bibliotecas python + Pyscript/Pyodide

## Critérios de Aprovação
- Compatível com SQLite3 ou proposição de alguma alternativa.
- Compatível com Python ou proposição de alguma alternativa.

**Comment by Danilo-Carvalho-Antunes** [comment]
O dashboard creator foi o framework Dash diretamente da linguagem Python.
