### ISSUE TITLE
Criar Home

### ISSUE THREAD

**Issue by JoaoBarreto03** [fga-eps-mds/2022-2-Squad06#50]
## Descrição
Criar a página inicial do projeto com React.

## Tarefas
- [x] Colocar imagem
- [x] Descrição do projeto

## Critérios de Aprovação
- Ser fiel ao protótipo
- Todos aprovarem

**Comment by Raphides** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Oficial-636ecc9a72dcd5dca72fdcb2/issues/fga-eps-mds/2022-2-UnBoard/50?planning-poker) with Zenhub @guilhermekishimoto @YuriBre

**Comment by JoaoBarreto03** [comment]
Pagina Home finalizada
