### ISSUE TITLE
Criar a página que receberá os dashboards

### ISSUE THREAD

**Issue by JoaoBarreto03** [fga-eps-mds/2022-2-Squad06#51]
## Descrição
Estruturação da página de dashboards.

## Tarefas
- [x] Incluir a Sidebar
- [x] Criar a barra de pesquisa
- [x] Incluir gráficos
- [ ] Adicionar informações sobre concorrência e nota de corte

## Critérios de Aprovação
- A página deve estar funcionando para todos os cursos
- A barra de pesquisa deve sugerir o curso a ser pesquisado
- Aprovação de todos os membros

**Comment by Raphides** [comment]
Barra de pesquisa já feita. Encontra-se na branch _backend_, pasta _backend_
Se todos aprovarem, em breve farei uma pull request do arquivo
