### ISSUE TITLE
Atualização da Barra de Pesquisa

### ISSUE THREAD

**Issue by Raphides** [fga-eps-mds/2022-2-Squad06#58]
## Descrição
Com a diminuição de pesquisa, alguns arquivos devem ser modificados. A barra de pesquisa é uma delas, sendo necessário diminuir o alcance da sua pesquisa.

## Tarefas
- [x] Trocar leitura de base de dados por leitura de planilhas.
- [x] Redimensionamento da classe Cursos_Repositórios (agora chamado Cursos_Lista)
- [x] Reimplementação dos testes unitários associados.

## Critérios de Aprovação
- Testes aprovados
- Classe Cursos_Lista suporta a leitura das planilhas de todos os anos.

**Comment by YuriBre** [comment]
Acredito que as planilhas dos anos restantes (2015, 2016, 2017, 2018) precisam ser analisadas, pois divergem das demais
