### ISSUE TITLE
Implementação Post Mortem

### ISSUE THREAD

**Issue by Raphides** [fga-eps-mds/2022-2-Squad06#64]
## Descrição
Criar o Post Mortem geral e uma impressão pessoal de cada um e inserir na pasta *Docs/Post Mortem*

## Tarefas
- [x] #65
- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71

## Critérios de Aprovação
- Estar na pasta Docs/Post Mortem
- Preferencialmente em Markdown (ou HTML)
- Apresentar expectativas, impressões e dicas.

**Comment by JoaoBarreto03** [comment]
Post Mortem concluidos e colocados na GitPage
