### ISSUE TITLE
Atividades iniciais 

### ISSUE THREAD

**Issue by Danilo-Carvalho-Antunes** [fga-eps-mds/2022-2-Squad06#8]
## Tarefas
- [x] Definir quais dados usar para a criação do Parse.
- [x] Introdução e escolha  da arquitetura para criação da parte web do produto. 
- [x] Divisões de equipe para melhor otimização.

## Critérios de Aprovação
- Apresentação dos resultados na cerimônia semanal.
- Revisão de Sprint 0.

**Comment by Raphides** [comment]
Essa issue será fechada e dividida em outras duas por sua extensão maior do que o esperado.
